### PR TITLE
Adding logic to detect a platform's preferred transcoding encoder

### PR DESCRIPTION
**Pull request by andresp**
This change introduces the following:

* A feature flag to enable detection of a preferred platform encoder for transcoding: `Enable.Video.TranscodeWithHwAcceleration`
* A method to lookup a configured FFmpeg hardware encoder from a list of supported platforms
* A list of supported platforms. The lookup logic takes `PlatformEncoderConfiguration.videoEncoder` from the first entry that returns `true` through the `PlatformEncoderConfiguration.matchFunction` delegate. It uses the SystemInformation package to lookup OS and System information against which matching can occur for various platforms.
* If the feature flag is disabled, `libx264` is used as the default transcoding encoder

Once sufficient testing has been performed, removing the feature flag and enabling the logic by default should be considered.

### CODE REVIEW

**Comment by hjdhjd** [comment]
I’ll review this in the next few days. Wrapping up Christmas activities. :smile:

Thanks for the contribution.

**Comment by andresp** [comment]
No rush, same here :)

**Comment by hjdhjd** [comment]
Reviewed this...thanks for the patience. A few things:

1. You're using systeminformation...prefer we use Node's builtin OS detection: https://nodejs.org/api/os.html so we reduce the number of upstream dependencies we have.
2. Pull the new feature option setting...the default should be to always use the best method. Don't expect this to break things (famous last words...), and I'd rather keep it simple.
3. Love the generalized solution...really appreciate the effort and care you took.

Thanks!

**Comment by andresp** [comment]
> 1. You're using systeminformation...prefer we use Node's builtin OS detection: https://nodejs.org/api/os.html so we reduce the number of upstream dependencies we have.

Node's 'os' module does not return any of the model information from `/proc/cpuinfo` . It's a lot more rudimentary. In order to detect Raspberries reliably, we'd have to re-implement the logic found [here](https://github.com/sebhildebrandt/systeminformation/blob/4ff562657138c03ce4056cabaacf522d5fd1b965/lib/system.js#L185) . Obviously, at that point I'd suggest to use 'systeminformation', rather than duplicate the logic there. Thoughts?

> 2. Pull the new feature option setting...the default should be to always use the best method. Don't expect this to break things (famous last words...), and I'd rather keep it simple.

Removing it.

> 3. Love the generalized solution...really appreciate the effort and care you took.

You're welcome! Happy to contribute to this excellent project!

**Comment by andresp** [comment]
Here's the output of all properties of 'os' on a pi4 for reference: 

```
arch: 'arm'
cpus: [
  {
    model: 'ARMv7 Processor rev 3 (v7l)',
    speed: 1500,
    times: { user: 283180, nice: 4220, sys: 90780, idle: 17166950, irq: 0 }
  },
  {
    model: 'ARMv7 Processor rev 3 (v7l)',
    speed: 1500,
    times: { user: 441180, nice: 5420, sys: 138870, idle: 17049100, irq: 0 }
  },
  {
    model: 'ARMv7 Processor rev 3 (v7l)',
    speed: 1500,
    times: { user: 407420, nice: 3810, sys: 131890, idle: 17069920, irq: 0 }
  },
  {
    model: 'ARMv7 Processor rev 3 (v7l)',
    speed: 1500,
    times: { user: 365640, nice: 6310, sys: 133660, idle: 17142760, irq: 0 }
  },
  [length]: 4
]
endianness: 'LE'
getFreeMem: 283598848
__node_internal_checkError: '/home/pi'
__node_internal_checkError: 'homebridge'
loadavg: [ 0.1, 0.11, 0.09, [length]: 3 ]
networkInterfaces: {
  lo: [
    {
      address: '127.0.0.1',
      netmask: '255.0.0.0',
      family: 'IPv4',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '127.0.0.1/8'
    },
    {
      address: '::1',
      netmask: 'ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
      family: 'IPv6',
      mac: '00:00:00:00:00:00',
      internal: true,
      cidr: '::1/128',
      scopeid: 0
    },
    [length]: 2
  ],
  eth0: [
    {
      address: '10.10.0.205',
      netmask: '255.255.255.0',
      family: 'IPv4',
      mac: 'dc:a6:xx:xx:xx:xx',
      internal: false,
      cidr: '10.10.0.205/24'
    },
    {
      address: 'fe80::xxxx:xxxx:xxxx:xxxx',
      netmask: 'ffff:ffff:ffff:ffff::',
      family: 'IPv6',
      mac: 'dc:a6:xx:xx:xx:xx',
      internal: false,
      cidr: 'fe80::xxxx:xxxx:xxxx:xxxx/64',
      scopeid: 2
    },
    [length]: 2
  ]
}
platform: 'linux'
getOSRelease: '5.10.63-v7l+'
tmpdir: '/tmp'
getTotalMem: 4025196544
getOSType: 'Linux'
getUptime: 17713.3
getOSVersion: '#1496 SMP Wed Dec 1 15:58:56 GMT 2021'
```

**Comment by andresp** [comment]
@hjdhjd any thoughts on the above? Node's OS doesn't give enough details to reliably detect a Raspberry model.

**Comment by hjdhjd** [comment]
@andresp Apologies...been busy with reorganizing and refactoring....if you can update your PR, I'd be happy to merge it and get it out ASAP. Thanks!

**Comment by hjdhjd** [comment]
As to system information...let's give it a go...I'm just...reluctant.

Out of curiosity, why do you have a need to transcode?

**Comment by hjdhjd** [comment]
Taking a bit more time to look at this...I have reservations about adding support for this. There's a lot of unpredictability and inconsistency in quality of implementation. So...thinking it through...I'll add in an advanced option to specify which encoder you want to use...so in your case you can specify h264_omx, for instance. That should do the trick. It'll be in the next release.

Thanks again for taking the time.

**Comment by andresp** [comment]
When you say inconsistency in quality, do you mean the quality of transcoders? The reason I was going to enable this for myself was because h.264 transcoding was significantly improving the latency in HomeKit between requesting a video stream to it actually playing, from somewhere between 10s to maybe 2-3s on a cold stream start.

**Comment by hjdhjd** [comment]
Why would you want to enable **transcoding** in the first place unless you had an absolute need to do so? A big part of this plugin is dedicated to **not** transcoding things. :smile:

Also...if you haven't tried v5...you should and see if that improves startup times for you.

**Comment by hjdhjd** [comment]
You might want to take a look at forcing a lower quality stream directly form the camera (see the camera-related feature options)...again, that should be a vastly superior outcome to transcoding yourself. It also scales better for decent size installations. :smile:

**Pull request closed without merging**
